name: Deploy Backend to Docker Hub

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for backend service
        run: docker build -f Dockerfile.core -t igrowker/i004-mindup-back-core:latest .

      - name: Push Docker image to Docker Hub
        run: docker push igrowker/i004-mindup-back-core:latest

      - name: Build Docker image for backend service
        run: docker build -f Dockerfile.chat -t igrowker/i004-mindup-back-chat:latest .

      - name: Push Docker image to Docker Hub
        run: docker push igrowker/i004-mindup-back-chat:latest

      - name: Build Docker image for backend service
        run: docker build -f Dockerfile.eureka -t igrowker/i004-mindup-back-eureka:latest .

      - name: Push Docker image to Docker Hub
        run: docker push igrowker/i004-mindup-back-eureka:latest
     
      - name: Build Docker image for backend service
        run: docker build -f Dockerfile.gateway -t igrowker/i004-mindup-back-gateway:latest .

      - name: Push Docker image to Docker Hub
        run: docker push igrowker/i004-mindup-back-gateway:latest
