services:
  eureka:
    build:
      context: .
      dockerfile: Dockerfile.eureka
    container_name: mindup-eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8761
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
    networks:
      - mindup-network
    restart: always
  
  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    container_name: mindup-chat
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8088
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
    networks:
      - mindup-network
    depends_on:
      - eureka
    restart: always

  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: mindup-core
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8089
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
      - CORE_JWT_EXPIRATION_TIME=${CORE_JWT_EXPIRATION_TIME}
      - CORE_JWT_SECRET_KEY=${CORE_JWT_SECRET_KEY}
      - CORE_BBDD_URL=${CORE_BBDD_URL}
      - CORE_DB_USERNAME=${CORE_DB_USERNAME}
      - CORE_DB_PASSWORD=${CORE_DB_PASSWORD}
    networks:
      - mindup-network
    depends_on:
      - eureka
    restart: always

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: mindup-gateway
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
      - SERVER_PORT=8090
      - GATEWAY_JWT_SECRET_KEY=${GATEWAY_JWT_SECRET_KEY}
      - GATEWAY_JWT_EXPIRATION=${GATEWAY_JWT_EXPIRATION}
    networks:
      - mindup-network
    depends_on:
      - eureka
    restart: always

networks:
  mindup-network:
    driver: bridge
