services:
  eureka:
    build:
      context: .
      dockerfile: Dockerfile.eureka
    container_name: mindup-eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8761
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
    networks:
      - mindup-network

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    container_name: mindup-chat
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8088
      - CHAT_HOSTNAME=${CHAT_HOSTNAME}
      - MONGO_URI=${CHAT_MONGO_URI}
      - MONGO_DB=${CHAT_MONGO_DB}
    networks:
      - mindup-network
    depends_on:
      - eureka
      - mongo

  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: mindup-core
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8089
      - CORE_HOSTNAME=${CORE_HOSTNAME}
      - CORE_JWT_SECRET_KEY=${CORE_JWT_SECRET_KEY}
      - CORE_BBDD_URL=${CORE_BBDD_URL}
      - CORE_DB_USERNAME=${CORE_DB_USERNAME}
      - CORE_DB_PASSWORD=${CORE_DB_PASSWORD}
    networks:
      - mindup-network
    depends_on:
      - eureka
      - postgres

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: mindup-gateway
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8090
      - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
      - GATEWAY_JWT_SECRET_KEY=${GATEWAY_JWT_SECRET_KEY}
      - GATEWAY_JWT_EXPIRATION=${GATEWAY_JWT_EXPIRATION}
    networks:
      - mindup-network
    depends_on:
      - eureka

  mongo:
    image: mongo:latest
    container_name: mindup-mongo
    ports:
      - "27017:27017"
    networks:
      - mindup-network
    volumes:
      - mindup-mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: mindup-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mindupdb
    ports:
      - "5432:5432"
    networks:
      - mindup-network
    volumes:
      - mindup-postgres-data:/var/lib/postgresql/data

networks:
  mindup-network:
    driver: bridge

volumes:
  mindup-mongo-data:
    driver: local
  mindup-postgres-data:
    driver: local

