name: Deploy Backend to Docker Hub and EC2

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker images for backend services
      - name: Build and Push Docker images for backend services
        run: |
          docker build -f Dockerfile.core -t igrowker/i004-mindup-back-core:${{ github.sha }} .
          docker tag igrowker/i004-mindup-back-core:${{ github.sha }} igrowker/i004-mindup-back-core:latest
          docker push igrowker/i004-mindup-back-core:${{ github.sha }}
          docker push igrowker/i004-mindup-back-core:latest

          docker build -f Dockerfile.chat -t igrowker/i004-mindup-back-chat:${{ github.sha }} .
          docker tag igrowker/i004-mindup-back-chat:${{ github.sha }} igrowker/i004-mindup-back-chat:latest
          docker push igrowker/i004-mindup-back-chat:${{ github.sha }}
          docker push igrowker/i004-mindup-back-chat:latest

          docker build -f Dockerfile.eureka -t igrowker/i004-mindup-back-eureka:${{ github.sha }} .
          docker tag igrowker/i004-mindup-back-eureka:${{ github.sha }} igrowker/i004-mindup-back-eureka:latest
          docker push igrowker/i004-mindup-back-eureka:${{ github.sha }}
          docker push igrowker/i004-mindup-back-eureka:latest

          docker build -f Dockerfile.gateway -t igrowker/i004-mindup-back-gateway:${{ github.sha }} .
          docker tag igrowker/i004-mindup-back-gateway:${{ github.sha }} igrowker/i004-mindup-back-gateway:latest
          docker push igrowker/i004-mindup-back-gateway:${{ github.sha }}
          docker push igrowker/i004-mindup-back-gateway:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > mindup.pem
          chmod 600 mindup.pem

      - name: Copy Docker Compose to EC2
        run: |
          scp -i mindup.pem -o StrictHostKeyChecking=no docker-compose.yml admin@${{ secrets.EC2_PUBLIC_IP }}:/home/admin/backend/


      - name: Deploy Backend on EC2 with Docker Compose
        run: |
          # Ejecutar Docker Compose pasando las variables de entorno directamente
          ssh -i mindup.pem -o StrictHostKeyChecking=no admin@${{ secrets.EC2_PUBLIC_IP }} "
            cd /home/admin/backend && 
            sudo docker-compose pull && 
            sudo docker-compose down && 
            sudo SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }} \
            EUREKA_HOSTNAME=${{ secrets.EUREKA_HOSTNAME }} \
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            CHAT_HOSTNAME=${{ secrets.CHAT_HOSTNAME }} \
            CHAT_MONGO_URI=${{ secrets.CHAT_MONGO_URI }} \
            CORE_HOSTNAME=${{ secrets.CORE_HOSTNAME }} \
            CORE_JWT_SECRET_KEY=${{ secrets.CORE_JWT_SECRET_KEY }} \
            CORE_BBDD_URL=${{ secrets.CORE_BBDD_URL }} \
            CORE_DB_USERNAME=${{ secrets.CORE_DB_USERNAME }} \
            CORE_DB_PASSWORD=${{ secrets.CORE_DB_PASSWORD }} \
            GATEWAY_HOSTNAME=${{ secrets.GATEWAY_HOSTNAME }} \
            GATEWAY_JWT_SECRET_KEY=${{ secrets.GATEWAY_JWT_SECRET_KEY }} \
            GATEWAY_JWT_EXPIRATION=${{ secrets.GATEWAY_JWT_EXPIRATION }} \
            MONGO_URI=${{ secrets.MONGO_URI }} \
            MONGO_DB=${{ secrets.MONGO_DB }} \
            POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            COMPOSE_HTTP_TIMEOUT=${{ secrets.COMPOSE_HTTP_TIMEOUT }} \
            sudo docker-compose up -d && 
            cd /home/admin/actions-runner && 
            ./run.sh
          "
